name: monitoring

networks:
  placement-network:
    external: true
  dokploy-network:
    external: true

volumes:
  signoz-clickhouse:
    driver: local
  signoz-data:
    driver: local

services:
  signoz:
    image: signoz/signoz-standalone:latest
    container_name: signoz
    restart: unless-stopped
    privileged: true
    ports:
      - "${SIGNOZ_PORT:-8080}:8080"
      - "${OTEL_GRPC_PORT:-4317}:4317"
      - "${OTEL_HTTP_PORT:-4318}:4318"
    volumes:
      - signoz-clickhouse:/var/lib/clickhouse
      - signoz-data:/var/lib/signoz
    networks:
      - placement-network
      - dokploy-network