http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: placement-main-backend
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["placement-main-backend"]
    relabel_configs:
      - target_label: job
        replacement: placement-main-backend
      - target_label: container
        replacement: placement-main-backend

  - job_name: placement-background
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["placement-background"]
    relabel_configs:
      - target_label: job
        replacement: placement-background
      - target_label: container
        replacement: placement-background

  - job_name: placement-subsystem
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["placement-subsytem"]
    relabel_configs:
      - target_label: job
        replacement: placement-subsystem
      - target_label: container
        replacement: placement-subsystem