global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    env: production

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]

  # Redpanda exposes Prometheus metrics on its admin port
  - job_name: redpanda
    static_configs:
      - targets: ["redpanda:9644"]
    metrics_path: /metrics
